version: '3'
services:
  web:
    container_name: angular
    image: 40022364/web-chat-application_web:latest
    ports:
      - '80:80'
    links:
      - node
  node:
    container_name: node
    restart: always #container will always restart
    image: 40022364/web-chat-application_node:latest2
    ports:
      - '3000:3000' #will map port 80 of our machine to port 3000 of docker container
    links:
      - mongo #to link our app service/container to our mongo service/container
  mongo:
    container_name: mongo
    image: mongo #will pull the image from dockerhub
    ports:
      - '27017:27017'
