version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always #container will always restart
    build: . #looks in the current directory for Dockerfile and builds the image
    ports:
      - '80:3000' #will map port 80 of our machine to port 3000 of docker container
    links:
      - mongo #to link our app service/container to our mongo service/container
  mongo:
    container_name: mongo
    image: mongo #will pull the image from dockerhub
    ports:
      - '27017:27017'
